version: '3'

services:
  db:
    build:
      context: mysql
    container_name: db
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - mainNetwork
    restart: always
    tty: true

  server:
    build:
      context: server
    container_name: server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node /usr/src/server/index.js
    networks:
      - mainNetwork  
    # ports:
    #   - 3000:3000
    depends_on:
      - db
    tty: true

  web:
    build:
      context: web
    container_name: web
    networks:
      - mainNetwork  
    ports:
      - 8080:80
    depends_on:
      - server
    restart: always
    tty: true

networks:
  mainNetwork:
    driver: bridge